[package]
name = "one_click_optimizer"
version = "0.1.0"
authors = ["sophgn <sophgn@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.16.2"
